<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <Version>0.8.1</Version>
    <Description>ModArchiveBrowser</Description>
    <PackageProjectUrl>https://github.com/Noevain/ModArchiveBrowser</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="SharpCompress" Version="1.0.0" />
    <PackageReference Include="Penumbra.Api" Version="5.15.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ModArchiveBrowser.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
